---
Capybara:
  Enabled: true
  DocumentationBaseURL: https://docs.rubocop.org/rubocop-capybara
  Include: &1
    - "**/*_spec.rb"
    - "**/spec/**/*"
    - "**/test/**/*"
    - "**/*_steps.rb"
    - "**/features/step_definitions/**/*"

Capybara/ClickLinkOrButtonStyle:
  Description: Checks for click button or link style.
  Enabled: pending
  VersionAdded: '2.19'
  EnforcedStyle: strict
  SupportedStyles:
    - strict
    - link_or_button
  Reference: https://www.rubydoc.info/gems/rubocop-capybara/RuboCop/Cop/Capybara/ClickLinkOrButtonStyle

Capybara/CurrentPathExpectation:
  Description: Checks that no expectations are set on Capybara's `current_path`.
  Enabled: true
  VersionAdded: '1.18'
  VersionChanged: '2.0'
  Reference: https://www.rubydoc.info/gems/rubocop-capybara/RuboCop/Cop/Capybara/CurrentPathExpectation

Capybara/MatchStyle:
  Description: Checks for usage of deprecated style methods.
  Enabled: pending
  VersionAdded: '2.17'
  Reference: https://www.rubydoc.info/gems/rubocop-capybara/RuboCop/Cop/Capybara/MatchStyle

Capybara/NegationMatcher:
  Description: Enforces use of `have_no_*` or `not_to` for negated expectations.
  Enabled: pending
  VersionAdded: '2.14'
  EnforcedStyle: not_to
  SupportedStyles:
    - have_no
    - not_to
  Reference: https://www.rubydoc.info/gems/rubocop-capybara/RuboCop/Cop/Capybara/NegationMatcher

Capybara/NegationMatcherAfterVisit:
  Description: Do not allow negative matchers to be used immediately after `visit`.
  Enabled: pending
  VersionAdded: "<<next>>"
  Reference: https://www.rubydoc.info/gems/rubocop-capybara/RuboCop/Cop/Capybara/NegationMatcherAfterVisit

Capybara/SpecificActions:
  Description: Checks for there is a more specific actions offered by Capybara.
  Enabled: pending
  VersionAdded: '2.14'
  Reference: https://www.rubydoc.info/gems/rubocop-capybara/RuboCop/Cop/Capybara/SpecificActions

Capybara/SpecificFinders:
  Description: Checks if there is a more specific finder offered by Capybara.
  Enabled: pending
  VersionAdded: '2.13'
  Reference: https://www.rubydoc.info/gems/rubocop-capybara/RuboCop/Cop/Capybara/SpecificFinders

Capybara/SpecificMatcher:
  Description: Checks for there is a more specific matcher offered by Capybara.
  Enabled: pending
  VersionAdded: '2.12'
  Reference: https://www.rubydoc.info/gems/rubocop-capybara/RuboCop/Cop/Capybara/SpecificMatcher

Capybara/VisibilityMatcher:
  Description: Checks for boolean visibility in Capybara finders.
  Enabled: true
  VersionAdded: '1.39'
  VersionChanged: '2.0'
  Reference: https://www.rubydoc.info/gems/rubocop-capybara/RuboCop/Cop/Capybara/VisibilityMatcher

Capybara/RSpec:
  Enabled: true
  Include: *1

Capybara/RSpec/HaveSelector:
  Description: Use `have_css` or `have_xpath` instead of `have_selector`.
  Enabled: pending
  DefaultSelector: css
  VersionAdded: '2.19'
  Reference: https://www.rubydoc.info/gems/rubocop-capybara/RuboCop/Cop/Capybara/RSpec/HaveSelector

Capybara/RSpec/PredicateMatcher:
  Description: Prefer using predicate matcher over using predicate method directly.
  Enabled: pending
  Strict: true
  EnforcedStyle: inflected
  AllowedExplicitMatchers: []
  SupportedStyles:
    - inflected
    - explicit
  VersionAdded: '2.19'
  Reference: https://www.rubydoc.info/gems/rubocop-capybara/RuboCop/Cop/Capybara/RSpec/PredicateMatcher
